name: Deploy Apache Hop Project

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy and Run Hop Workflow
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to Ubuntu server and run Apache Hop
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            /opt/hop-projects/deploy-hop-project.sh
